{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-types-genomics
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - samtools
    - q2-types {{ qiime2_epoch }}.*
    - qiime2 {{ qiime2_epoch }}.*

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_types_genomics
    - qiime2.plugins.types_genomics
  commands:
    - pytest --cov q2_types_genomics --pyargs q2_types_genomics

about:
  home: https://github.com/bokulich-lab/q2-types-genomics
  license: BSD-3-Clause
  license_family: BSD
